/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    DarkThemeToggle: typeof import('./src/components/DarkThemeToggle.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
